/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jaimefreire' at '9/12/16 9:50 PM' with Gradle 3.0
 *
 * @author jaimefreire, @date 9/12/16 9:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
